site_name: alvsanand.com
site_url: https://alvsanand.com
site_author: Alvaro Santos Andres
site_description: >-
  This is the personal blog of Alvaro Santos

theme:
  name: material
  icon:
    logo: "fontawesome/brands/microblog"
  palette:
    primary: white
    scheme: default
  features:
    - content.code.copy
    - content.tooltips
    - navigation.tabs
    - navigation.top
    - navigation.expand

extra_css:
  - assets/custom.css

markdown_extensions:
  - attr_list
  - md_in_html
  - toc:
      toc_depth: 0

plugins:
  - blog:
      archive: false
      categories_toc: false
  - macros:
      include_dir: .
  - glightbox

# Page tree
nav:
  - About: index.md
  - Blog:
      - blog/index.md
