name: sync-pages
on:
  push:
    branches: [ gh-pages ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to external repository
        uses: cpina/github-action-push-to-another-repository@main
        with:
          source-directory: .
          target-directory: .
          destination-github-username: alvsanand
          destination-repository-name: alvsanand.github.io
          user-email: alvsanand@gmail.com
          target-branch: "gh-pages"
          create-target-branch-if-needed: true
